Repository icarusgk/vuejs-spanish-docs, pull requests merged in 2024-05, with the labels that each got.

#45 docs(es): Oct 17
  .vitepress/inlined-scripts/restorePreference.js
  src/about/releases.md
  src/api/built-in-components.md
  src/guide/components/registration.md
  src/guide/reusability/composables.md
Labels: ready-to-merge

#46 docs(es): Oct 4 - Oct 15
  .vitepress/config.ts
  .vitepress/theme/components/Banner.vue
  .vitepress/theme/index.ts
  src/partners/partners.json
  src/public/images/partners/curotec-hero.jpg
  src/public/images/partners/curotec.png
  src/translations/index.md
Labels: documentation, ready-to-merge

#48 docs(es): Oct 18 - Oct 25
  package.json
  src/about/faq.md
  src/guide/best-practices/accessibility.md
  src/guide/typescript/overview.md
Labels: documentation, ready-to-merge

#50 docs(es): Oct 26 - Oct 31
  .vitepress/inlined-scripts/restorePreference.js
  .vitepress/theme/components/Banner.vue
  .vitepress/theme/index.ts
  src/guide/best-practices/accessibility.md
  src/guide/built-ins/transition.md
  src/guide/components/events.md
  src/guide/components/registration.md
  src/style-guide/rules-recommended.md
Labels: documentation

#54 docs(es): Nov 2 - Nov 5
  .vitepress/theme/components/VueMasteryBanner.vue
  .vitepress/theme/index.ts
  pnpm-lock.yaml
  src/about/team/TeamMember.vue
  src/guide/essentials/watchers.md
  src/guide/scaling-up/testing.md
  src/public/vuemastery/background-bubbles-vuemastery.svg
  src/public/vuemastery/lock-vuemastery.svg
  src/public/vuemastery/unlock-vuemastery.svg
  src/public/vuemastery/vuemastery-white.svg
Labels: documentation, need-review

#49 docs(es): Nov 6 - Nov 14
  .vitepress/theme/components/SponsorsGroup.vue
  .vitepress/theme/components/sponsors.ts
  pnpm-lock.yaml
  src/api/reactivity-core.md
  src/tutorial/src/step-10/App/template.html
Labels: documentation, need-review

#53 docs(es): Nov 15 - Nov 28
  .vitepress/theme/components/VueMasteryBanner.vue
  .vitepress/theme/index.ts
  pnpm-lock.yaml
  src/guide/reusability/composables.md
  src/guide/scaling-up/tooling.md
  src/public/vuemastery/background-bubbles-vuemastery.svg
  src/public/vuemastery/lock-vuemastery.svg
  src/public/vuemastery/unlock-vuemastery.svg
  src/public/vuemastery/vuemastery-white.svg
  src/translations/index.md
Labels: documentation

#55 docs(es): Nov 29 - Nov 30
  .vitepress/inlined-scripts/restorePreference.js
  .vitepress/theme/components/Banner.vue
  .vitepress/theme/index.ts
  .vitepress/theme/styles/index.css
  package.json
  pnpm-lock.yaml
  src/examples/ExampleRepl.vue
  src/guide/introduction.md
  src/style-guide/index.md
  src/style-guide/rules-essential.md
  src/style-guide/rules-recommended.md
  src/style-guide/rules-use-with-caution.md
  src/tutorial/TutorialRepl.vue
Labels: documentation, need-review

#57 docs(es): Dec 1 - Dec 4
  package.json
  pnpm-lock.yaml
  src/api/composition-api-dependency-injection.md
  src/guide/components/events.md
  src/guide/essentials/template-refs.md
  src/guide/scaling-up/testing.md
  src/guide/typescript/composition-api.md
Labels: documentation, need-review

#51 docs(es): Dec 6 - Dec 7
  .vitepress/config.ts
  .vitepress/theme/components/Home.vue
  src/guide/quick-start.md
  src/guide/typescript/overview.md
  src/partners/partners.json
  src/public/images/partners/dreamonkey-hero.png
  src/public/images/partners/dreamonkey.png
Labels: documentation
